apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-flights
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-flights
  project: default
  source:
    repoURL: 'https://github.com/IshanThakur13/argocd-open-flights.git'
    path: main
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true