apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  type: git
  url: 'https://github.com/IshanThakur13/argocd-open-flights.git'
  username: ishanthkr123@gmail.com
  password: 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